AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/BeginEndAlignment:
  Enabled: true

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/RescueEnsureAlignment:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedException:
  Enabled: false

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

Metrics:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - blue
    - delete_if

Style/CaseLikeIf:
  Enabled: false

Style/CombinableLoops:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/GlobalStdStream:
  Enabled: true

Style/GlobalVars:
  AllowedVariables: ['$ansi']

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/KeywordParametersOrder:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/StderrPuts:
  Enabled: false

Style/StringConcatenation:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  MinSize: 3
