language: c

os: osx
osx_image: xcode9.3

sudo: true

before_install:
  - yes yes | sudo rvm implode &
  - sudo rm -r ~/.rvmrc ~/.gemrc ~/.bashrc ~/.bash_profile ~/.bundle ~/.gem ~/.cocoapods ~/nvm &
  - brew uninstall --force $(brew ls) &
  - brew cask uninstall --force $(brew cask ls) &
  - wait
  - unset GEM_PATH
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" -- --force
install: ./.sh

notifications:
  email: false
