language: c

os: osx
osx_image: xcode9.3

sudo: true

before_install:
  - brew uninstall --force $(brew ls)
  - brew cask uninstall --force $(brew cask ls)
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" -- --force
install: ./.sh
