jobs:
  - job: Shellcheck
    pool:
      demands:
        - agent.os -equals Darwin
    steps:
      - bash: |
          set -e
          set -u
          set -o pipefail

          brew install shellcheck
          shellcheck .sh
        displayName: ShellCheck
  - job: RuboCop
    pool:
      demands:
        - agent.os -equals Darwin
    steps:
      - bash: |
          set -e
          set -u
          set -o pipefail

          gem install rubocop
          rubocop --color
        displayName: RuboCop
  - job: Dotfiles
    timeoutInMinutes: 200
    strategy:
      matrix:
        Catalina:
          vmImage: 'macOS-10.15'
    pool:
      vmImage: $(vmImage)
    steps:
      - bash: |
          set -e
          set -u
          set -o pipefail

          # Uninstall Gems.
          for gem in $(gem list --no-versions | grep -v \
                                                     -e 'bigdecimal' \
                                                     -e 'CFPropertyList' \
                                                     -e 'cmath' \
                                                     -e 'csv' \
                                                     -e 'date' \
                                                     -e 'dbm' \
                                                     -e 'did_you_mean' \
                                                     -e 'e2mmap' \
                                                     -e 'etc' \
                                                     -e 'fcntl' \
                                                     -e 'fiddle' \
                                                     -e 'fileutils' \
                                                     -e 'forwardable' \
                                                     -e 'io-console' \
                                                     -e 'ipaddr' \
                                                     -e 'irb' \
                                                     -e 'json' \
                                                     -e 'libxml-ruby' \
                                                     -e 'logger' \
                                                     -e 'matrix' \
                                                     -e 'minitest' \
                                                     -e 'mutex_m' \
                                                     -e 'net-telnet' \
                                                     -e 'nokogiri' \
                                                     -e 'openssl' \
                                                     -e 'ostruct' \
                                                     -e 'power_assert' \
                                                     -e 'prime' \
                                                     -e 'psych' \
                                                     -e 'rake' \
                                                     -e 'rexml' \
                                                     -e 'rdoc' \
                                                     -e 'rss' \
                                                     -e 'scanf' \
                                                     -e 'shell' \
                                                     -e 'sqlite3' \
                                                     -e 'stringio' \
                                                     -e 'strscan' \
                                                     -e 'sync' \
                                                     -e 'test-unit' \
                                                     -e 'thwait' \
                                                     -e 'tracer' \
                                                     -e 'webrick' \
                                                     -e 'xmlrpc' \
                                                     -e 'zlib' \
          ); do
            sudo gem uninstall --force --all --ignore-dependencies --executables "$gem"
          done

          # Uninstall Homebrew.
          sudo rm -rf /usr/local/miniconda &
          rm -rf /usr/local/lib/node_modules &
          rm -f /usr/local/bin/terminal-notifier

          if which brew &>/dev/null; then
            eval "$(brew list | xargs -I% echo 'brew uninstall --force --ignore-dependencies "%" &')"
            eval "$(brew cask list | xargs -I% echo '{ brew cask uninstall --force "%"; brew cask zap --force "%"; } &')"
            brew cask zap --force dotnet &
            wait
            /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" -- --force
          fi

          # Uninstall Xcode and Command Line Tools
          mkdir -p /tmp/trash
          for trash in /Applications/Xcode*.app /Library/Developer/CommandLineTools; do
            sudo mv "$trash" /tmp/trash/
          done
          sudo pkgutil --forget com.apple.pkg.CLTools_Executables
          sudo xcode-select --reset

          # Clean environment.
          for trash in ~/.DS_Store \
                       ~/.Trash/* \
                       ~/.android \
                       ~/.azcopy \
                       ~/.azure \
                       ~/.bash_history \
                       ~/.bash_profile \
                       ~/.bash_sessions \
                       ~/.bashrc \
                       ~/.cargo \
                       ~/.cocoapods \
                       ~/.conda \
                       ~/.config \
                       ~/.dotnet \
                       ~/.fastlane \
                       ~/.gem \
                       ~/.gitconfig \
                       ~/.gradle \
                       ~/.m2 \
                       ~/.mono \
                       ~/.npm \
                       ~/.npmrc \
                       ~/.nvm \
                       ~/.oracle_jre_usage \
                       ~/.packer.d \
                       ~/.rustup \
                       ~/.sh_history \
                       ~/.subversion \
                       ~/.sqlite_history \
                       ~/.vcpkg \
                       ~/.viminfo \
                       ~/.wget-hsts \
                       ~/.yarn \
                       ~/Microsoft \
                       ~/hostedtoolcache \
                       ~/*.txt; do
            if [ -e "$trash" ]; then
              mv "$trash" /tmp/trash/
            fi
          done

          # Delete broken symlinks.
          for exe in /usr/local/bin/*; do
            if [ -L "$exe" ] && ! [ -e "$exe" ]; then
              rm "$exe"
            fi
          done

          ls -al ~/
        displayName: Clean environment
      - bash: ./.sh
        displayName: Run `.sh`
        env:
          CI: 'true'
